### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ghost** [wwliao/bkheatmap#1]
1) Please provide table.txt for the example to work.

2) The package has trouble with this data:
df = pd.DataFrame(
{'L': {0: 0.07, 1: 0.27},
 'M': {0: 0.03, 1: 0.23},
 'R': {0: 0.08, 1: 0.32}}
)

**Comment by wwliao** [comment]
1. I've added a download link to the example in README.
2. The column/row indexes of DataFrame must be strings.
    It will work if
    df = pd.DataFrame(
    {'L': {'0': 0.07, '1': 0.27},
    'M': {'0': 0.03, '1': 0.23},
    'R': {'0': 0.08, '1': 0.32}}
    )
